
services:
  ai-service:
    build: ./ai-service
    container_name: devboard-ai-service
    ports:
      - "8000:8000"
    env_file:
      - ./ai-service/.env
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./ai-service
          ignore:
            - .venv/
            - __pycache__/
            - .git/
  

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "8081:8081"
   
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./task-service
          ignore:
            - target/
            - .git/

  client:
    build: ./client
    container_name: devboard-client
    
    ports:
      - "5173:80"
    # depends_on:
    #   - api-gateway
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./client
          ignore:
            - node_modules/
            - dist/
            - .git/
