
services:
  # auth-service:
  #   build: ./auth-service
  #   container_name: auth-service
  #   ports:
  #     - "8080:8080"
  #   restart: unless-stopped
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./auth-service
  #         ignore:
  #           - target/
  #           - .git/

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "8081:8081"
    # environment:
    #   - AUTH_SERVICE_URL=http://auth-service:8080
    
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./task-service
          ignore:
            - target/
            - .git/

  # api-gateway:
  #   build: ./api-gateway
  #   container_name: api-gateway
  #   ports:
  #     - "8060:8060"
  #   environment:
  #     - AUTH_SERVICE_URL=http://auth-service:8080
  #     - TASK_SERVICE_URL=http://task-service:8081
  #   depends_on:
  #     - auth-service
  #     - task-service
  #   restart: unless-stopped
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./api-gateway
  #         ignore:
  #           - target/
  #           - .git/

  client:
    build: ./client
    container_name: devboard-client
    
    ports:
      - "5173:80"
    # depends_on:
    #   - api-gateway
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./client
          ignore:
            - node_modules/
            - dist/
            - .git/
