import json
import os
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, status,HTTPException
from fastapi.responses import JSONResponse
from sqlmodel import Session, select,delete

from api.database import get_session
from api.security import get_current_user   # ← swap this import to whatever auth_routes.py actually uses
from api.groq_client import get_groq_client          # ← assumes groq_client.py exports a ready `client` — adjust name if it's different
from api.models import AgentConversation, AgentMessage
from api.models import MessageRequest, MessageResponse, ConversationResponse, AgentMessageOut,ExecuteActionRequest,PendingAction
from services.task_client import create_task, delete_task, update_task, get_task_by_id , get_tasks_by_owner , get_assigned_tasks
from tools.agent_tools import TOOLS

router = APIRouter(prefix="/agent", tags=["Agent"])

MODEL = "openai/gpt-oss-20b"

SYSTEM_PROMPT = """You are DevBoard AI, an automated assistant dedicated strictly to task management for DevBoard.

User Email: {user_email}
Today's Date: {today}

Scope & Capabilities:
- Supported Features: Managing tasks ONLY (fetching, creating, updating, deleting tasks).
- Unsupported Features: Project planning, calendar scheduling, notifications, emails, docs, or non-task management features.

Instructions & Rules:
1. Feature Bounds:
   - If a user asks to perform an action or use a feature outside task management (e.g., "create a plan", "schedule a meeting", "send an email"), clearly inform them: "That feature is not available yet."

2. Task Creation Rules:
   - Task creation requires a `title`.
   - Optional fields include `description`, `priority` (LOW, MEDIUM, HIGH), and `dueDate` (YYYY-MM-DD).
   - If a user requests to create a task without providing a title, ask them for the title. Mention that they can provide optional details or let you auto-generate reasonable defaults (e.g., setting priority to MEDIUM or drafting a description).
   - If a user asks what details are needed to create a task, state that only a `title` is strictly required, while `description`, `priority`, and `dueDate` are optional (and can be auto-generated by you upon request).

3. Output Formatting:
   - Keep responses concise, friendly, and structured in plain text or simple list format.
   - DO NOT output raw, unformatted markdown tables when listing tasks.
"""


MUTATING_TOOLS = {"create_task", "update_task", "delete_task"}



def _get_or_create_conversation(session: Session, user_email: str, conversation_id: int | None) -> AgentConversation:
    if conversation_id is not None:
        conversation = session.exec(
            select(AgentConversation).where(
                AgentConversation.id == conversation_id,
                AgentConversation.user_email == user_email,
            )
        ).first()
        if conversation is not None:
            return conversation
    conversation = AgentConversation(user_email=user_email)
    session.add(conversation)
    session.commit()
    session.refresh(conversation)
    return conversation


def _save_message(session: Session, conversation_id: int, role: str, content: str) -> AgentMessage:
    message = AgentMessage(conversation_id=conversation_id, role=role, content=content)
    session.add(message)
    session.commit()
    session.refresh(message)
    return message


def _trim_tasks(tasks: list[dict]) -> list[dict]:
    """Cuts prompt tokens by stripping non-essential fields and capping description lengths."""
    if not isinstance(tasks, list):
        return []
    
    trimmed = []
    for t in tasks:
        if isinstance(t, dict):
            desc = t.get("description") or ""
            # Truncate long descriptions to 80 chars for context efficiency
            short_desc = (desc[:77] + "...") if len(desc) > 80 else desc
            
            trimmed.append({
                "id": t.get("id"),
                "title": t.get("title"),
                "status": t.get("status"),
                "priority": t.get("priority"),
                "dueDate": t.get("dueDate"),
                "description": short_desc
            })
    return trimmed


@router.post("/message", response_model=MessageResponse)
def send_agent_message(
    request: MessageRequest,
    session: Session = Depends(get_session),
    user_email: str = Depends(get_current_user),
):
    try:
        conversation = _get_or_create_conversation(session, user_email, request.conversation_id)
        _save_message(session, conversation.id, "user", request.message)

        # Context window capping to save Groq tokens
        history = session.exec(
            select(AgentMessage)
            .where(AgentMessage.conversation_id == conversation.id)
            .order_by(AgentMessage.created_at.desc())
            .limit(6)
        ).all()
        history = list(reversed(history))

        groq_messages = [{
            "role": "system",
            "content": SYSTEM_PROMPT.format(
                user_email=user_email,
                today=datetime.now(timezone.utc).date().isoformat(),
            ),
        }]
        groq_messages += [{"role": m.role, "content": m.content} for m in history]

        groq_client = get_groq_client()
        response = groq_client.chat.completions.create(
            model=MODEL, messages=groq_messages, tools=TOOLS, tool_choice="auto"
        )
        choice = response.choices[0].message

        if choice.tool_calls:
            tool_call = choice.tool_calls[0]
            tool_name = tool_call.function.name
            args = json.loads(tool_call.function.arguments)

            # Intercept write actions for UI approval
            if tool_name in MUTATING_TOOLS:
                return MessageResponse(
                    reply=f"Approval needed to execute: {tool_name}",
                    conversation_id=conversation.id,
                    requires_approval=True,
                    pending_action=PendingAction(action_type=tool_name, arguments=args),
                )

            # --- READ-ONLY TOOL EXECUTIONS ---
            # --- READ-ONLY TOOL EXECUTIONS ---
            tasks = None
            if tool_name == "get_tasks":
                tasks = get_tasks_by_owner(user_email)
            elif tool_name == "get_assigned_tasks":
                tasks = get_assigned_tasks(user_email)

            if tasks is not None:
                groq_messages.append({
                    "role": "assistant",
                    "content": choice.content or "",
                    "tool_calls": [{
                        "id": tool_call.id,
                        "type": "function",
                        "function": {"name": tool_name, "arguments": tool_call.function.arguments}
                    }]
                })
                groq_messages.append({
                    "role": "tool",
                    "tool_call_id": tool_call.id,
                    "content": json.dumps(_trim_tasks(tasks)),
                })

                follow_up = groq_client.chat.completions.create(model=MODEL, messages=groq_messages)
                reply_text = follow_up.choices[0].message.content or "Here are your tasks:"

                _save_message(session, conversation.id, "assistant", reply_text)
                conversation.updated_at = datetime.now(timezone.utc)
                session.commit()

                # Return structured payload for Card rendering
                return MessageResponse(
                    reply=reply_text,
                    conversation_id=conversation.id,
                    data_type="TASK_LIST",
                    data=tasks
                )
                reply_text = choice.content or ""
        else:
            reply_text = choice.content or ""

        _save_message(session, conversation.id, "assistant", reply_text)
        conversation.updated_at = datetime.now(timezone.utc)
        session.commit()

        return MessageResponse(reply=reply_text, conversation_id=conversation.id)

    except Exception as e:
        return JSONResponse(status_code=500, content={"error": str(e)})


@router.get("/conversations")
def get_conversations(
    session: Session = Depends(get_session),
    user_email: str = Depends(get_current_user),
):
    try:
        conversations = session.exec(
            select(AgentConversation)
            .where(AgentConversation.user_email == user_email)
            .order_by(AgentConversation.updated_at.desc())
        ).all()

        return conversations

    except Exception as e:
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={"error": str(e)},
        )


@router.get(
    "/messages/{conversation_id}",
    response_model=ConversationResponse
)
def get_conversation_messages(
    conversation_id: int,
    session: Session = Depends(get_session),
    user_email: str = Depends(get_current_user),
):
    try:

        # First verify that this conversation belongs to this user
        conversation = session.exec(
            select(AgentConversation)
            .where(
                AgentConversation.id == conversation_id,
                AgentConversation.user_email == user_email
            )
        ).first()

        if conversation is None:
            return JSONResponse(
                status_code=404,
                content={"error": "Conversation not found"},
            )

        # Fetch messages only for this conversation
        messages = session.exec(
            select(AgentMessage)
            .where(
                AgentMessage.conversation_id == conversation_id
            )
            .order_by(
                AgentMessage.created_at.asc()
            )
        ).all()

        return ConversationResponse(
            messages=[
                AgentMessageOut(
                    role=m.role,
                    content=m.content,
                    created_at=m.created_at
                )
                for m in messages
            ]
        )

    except Exception as e:
        return JSONResponse(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={"error": str(e)},
        )


@router.delete("/delete/{conversation_id}")
def deleteConversation(
    conversation_id : int,
    session : Session = Depends(get_session),
    user_email : str = Depends(get_current_user)
    
):
    try :
        conversation = session.exec(
            select(AgentConversation)
            .where(
                AgentConversation.id == conversation_id,
                AgentConversation.user_email == user_email
                )
            
        ).first()
        if conversation is None:
                return JSONResponse(
                status_code=404,
                content={"error": "Conversation not found"},
                )

        session.exec(
            delete(AgentMessage)
            .where(
                AgentMessage.conversation_id == conversation_id
            )
        )

        session.exec(
            delete(AgentConversation)
            .where(AgentConversation.id == conversation_id)

        )

        session.delete(conversation)

        session.commit()

        return { "message": "Conversation deleted successfully" }



    except Exception as e :
        return JSONResponse(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                content={"error": str(e)},
        )




@router.post("/execute-action")
def execute_approved_action(
    req: ExecuteActionRequest,
    session: Session = Depends(get_session),
    user_email: str = Depends(get_current_user),
):
    try:
        args = req.arguments
        result_message = ""

        if req.action_type == "create_task":
            payload = {
                "title": args.get("title"),
                "description": args.get("description", ""),
                "priority": args.get("priority", "MEDIUM"),
                "dueDate": args.get("dueDate"),
                "ownerEmail": user_email,
            }
            res = create_task(payload)
            result_message = f"Task '{res.get('title')}' (ID: #{res.get('id')}) created successfully."

        elif req.action_type == "update_task":
            task_id = args.get("task_id")
            # Fetch existing entity so Spring Boot doesn't overwrite non-updated fields with NULL
            existing = get_task_by_id(task_id)
            if "status" in args:
                existing["status"] = args["status"]
            if "title" in args:
                existing["title"] = args["title"]

            update_task(task_id, existing)
            result_message = f"Task #{task_id} updated successfully."

        elif req.action_type == "delete_task":
            task_id = args.get("task_id")
            # delete_task will check ownership and throw HTTP 403 if user_email != ownerEmail
            delete_task(task_id, current_user_email=user_email)
            result_message = f"Task #{task_id} deleted successfully."

        else:
            raise HTTPException(status_code=400, detail="Invalid action type")

        _save_message(session, req.conversation_id, "assistant", result_message)
        return {"status": "success", "message": result_message}

    except Exception as e:
        return JSONResponse(status_code=500, content={"error": str(e)})